### ISSUE TITLE
Update event_stream to Clockwork v1.4.0

### ISSUE THREAD

**Issue by mwrites** [clockwork-xyz/examples#47]
Update the examples to 1.4.0:
- [ ] A major change on the deps, is that we are not relying on the clockwork fork of anchor anymore, so we can remove the [patches](https://github.com/clockwork-xyz/examples/pull/46/files#diff-1558aa9ee7e1ad39467822b32a37913dd06b564aca714a67f6d0823ba912c390)
- [ ] For the program handler: the SDK interface changed since [this](https://github.com/clockwork-xyz/clockwork/commit/c534cd9f4767664174bb5634982e9ee3d5f087c2#diff-d8b2bc9f3303d943e5be413a2c54965e6faa5836ccd597d12fa2a557df826608) and [this](https://github.com/clockwork-xyz/clockwork/commit/6ee9ac1545dcc64eb9f73046dbe2cf9aa5d6412e#diff-d8b2bc9f3303d943e5be413a2c54965e6faa5836ccd597d12fa2a557df826608)
- [ ] For the  client: The client should rely on `clockwork-client` instead of `clockwork-sdk`
- [ ] (Optional) Update the README and the corresponding code based on [this template](https://github.com/clockwork-xyz/clockwork/commit/c534cd9f4767664174bb5634982e9ee3d5f087c2#diff-)

You can use this [PR](https://github.com/clockwork-xyz/examples/pull/46/files) as a reference

**Comment by iamvon** [comment]
Hi @mwrites, I created a PR for this issue [here](https://github.com/clockwork-xyz/examples/pull/54). Please take a look!

**Comment by iamvon** [comment]
Hi @mwrites, I've created a PR for this issue [here](https://github.com/clockwork-xyz/examples/pull/54). Please take a look!

**Comment by mwrites** [comment]
Solved by https://github.com/clockwork-xyz/examples/pull/54
